services:
  mysql:
    image: docker.m.daocloud.io/library/mysql:8.0
    container_name: medisage-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: medisage
    ports:
      - "3306:3306"
    volumes:
      - medisage-mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro

volumes:
  medisage-mysql-data:
